insert into lecture_info (`name`, `created_at`) values ('special-lecture1', '2024-06-25'),
                                                      ('special-lecture2', '2024-06-10'),
                                                      ('special-lecture3', '2024-06-01'),
                                                      ('special-lecture4', '2024-06-30'),
                                                      ('special-lecture5', '2024-06-15'),
                                                      ('special-lecture6', '2024-06-08');

insert into lecture (`lecture_info_id`, `opened_at`, `user_limit`) values (1, '2024-06-25', 30),
                                                         (1, '2024-06-10', 40),
                                                         (2, '2024-06-01', 50),
                                                         (3, '2024-06-30', 30),
                                                         (3, '2024-06-15', 40),
                                                         (4, '2024-06-08', 20),
                                                         (5, '2024-06-08', 20),
                                                         (6, '2024-06-08', 20);

insert into user (`name`) values ('Catie'),
                                       ('Star'),
                                       ('Petronella'),
                                       ('Ellie'),
                                       ('Lutero'),
                                       ('Findley'),
                                       ('Randy'),
                                       ('Elnora'),
                                       ('Ava'),
                                       ('Loni'),
                                       ('Chaddy'),
                                       ('Rudiger'),
                                       ('Garrard'),
                                       ('Shelley'),
                                       ('Mechelle'),
                                       ('Ari'),
                                       ('Eloisa'),
                                       ('Lilllie'),
                                       ('Janifer'),
                                       ('Pincus'),
                                       ('Torrence'),
                                       ('Gayleen'),
                                       ('Corene'),
                                       ('Romona'),
                                       ('Flinn'),
                                       ('Kaleb'),
                                       ('Rolfe'),
                                       ('Stephen'),
                                       ('Elva'),
                                       ('Shadow'),
                                       ('Melodee'),
                                       ('Whitaker'),
                                       ('Early'),
                                       ('Chester'),
                                       ('Jasen'),
                                       ('Lorrayne'),
                                       ('Maureen'),
                                       ('Guillema'),
                                       ('Ilyssa'),
                                       ('Elaina'),
                                       ('Elias'),
                                       ('Louella'),
                                       ('Gwenny'),
                                       ('Linnea'),
                                       ('Burty'),
                                       ('Tab'),
                                       ('Kissie'),
                                       ('Wilfred'),
                                       ('Bail'),
                                       ('Ursa'),
                                       ('Conny'),
                                       ('Tiena'),
                                       ('Lucina'),
                                       ('Hermine'),
                                       ('Tulley'),
                                       ('Dall'),
                                       ('Abel'),
                                       ('Gayleen'),
                                       ('Shawn'),
                                       ('Kelvin'),
                                       ('Law'),
                                       ('Adams'),
                                       ('Cesya'),
                                       ('Karly'),
                                       ('Niel'),
                                       ('Cordy'),
                                       ('Kania'),
                                       ('Xenos'),
                                       ('Kelsey'),
                                       ('Reginald'),
                                       ('Shamus'),
                                       ('Guido'),
                                       ('Eziechiele'),
                                       ('Rogerio'),
                                       ('Kial'),
                                       ('Leigh'),
                                       ('Clarke'),
                                       ('Magnum'),
                                       ('Karlis'),
                                       ('Car'),
                                       ('Wilton'),
                                       ('Berry'),
                                       ('Harlan'),
                                       ('Melisande'),
                                       ('Merralee'),
                                       ('Quill'),
                                       ('Putnem'),
                                       ('Daniel'),
                                       ('Toddie'),
                                       ('Althea'),
                                       ('Annabal'),
                                       ('Suzanne'),
                                       ('Bettina'),
                                       ('Meagan'),
                                       ('Andris'),
                                       ('Frederick'),
                                       ('Allene'),
                                       ('Nappie'),
                                       ('Jervis'),
                                       ('Avrit');
